### ISSUE TITLE
Use in browser?

### ISSUE THREAD

**Issue by oyeanuj** [dfcreative/nogl#2]
Hi @dfcreative, thank you for creating this. Is there a version of this that can be used as a polyfill for browsers that are not supporting WebGL?

My usecase is trying to use https://github.com/gre/gl-react but with support for as many browsers as I can.

**Comment by dy** [comment]
Hi @oyeanuj! This lib is not a polyfill, it is just a shim with fake properties, it has nothing to do with actual webgl functionality.
You may want to look at https://github.com/humu2009/tinygl.js if you really need a polyfill. Though I doubt there is any use in that, considering that making GPU things single-threaded is thousands of times slower, moreover on browsers not supporting webgl.
